#!/usr/bin/env python3
"""Inline selected SKILL.md bodies into ~/.hermes/SOUL.md.

Why this exists
---------------
Hermes advertises skills to the model as name + description, and the model
loads a body with ``skill_view(name=…)``.  Each of those is a full round trip
to the model, and the RGS+ helpdesk agent needs the same skills on essentially
every turn.  Measured on 2026-08-28 (``~/.hermes/logs/agent.log``), a typical
turn spent its first three API calls doing nothing but climbing the skill
ladder:

    #1  20k in  →  skill_view(customer-service) + skill_view(confluence-…)
    #2  28k in  →  skill_view(rgsplus-handleiding)
    #3  45k in  →  the actual work

Tool execution across the whole log was 134s against 3531s of model latency,
so the ladder is not slow because reading files is slow — it is slow because
each rung costs a 2-10s generation.  Inlining the bodies into SOUL.md (which
is always injected as the identity slot) removes rungs #1 and #2 and makes
the whole prefix identical across requests, so it can be prompt-cached.

Token cost is roughly a wash: the turn used to arrive at ~45k input by call
#3 anyway.  We now pay it at call #1 and stop paying for the extra calls.

Contract
--------
The generated text lives inside a marked block, following the
``ORCHESTRATION:BEGIN/END`` idiom already used in the client SOUL.md.
Everything outside the block is preserved verbatim, so a SOUL the customer
edited through the webui survives a container restart.  Re-running replaces
the block in place.

Skills are NOT removed from ~/.hermes/skills — ``skill_view`` stays available
as a fallback and for anything not preloaded.  The block header tells the
model not to spend a round trip re-reading what is already in front of it.

Usage:
    preload-skills.py --soul ~/.hermes/SOUL.md \
                      --skills-dir ~/.hermes/skills \
                      --skills rgsplus-handleiding,customer-service,...

Exit status is 0 even when nothing could be inlined: a missing skill is a
warning, never a reason to fail container start.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

BEGIN = ("<!-- PRELOADED-SKILLS:BEGIN (auto-generated by "
         "agent/scripts/preload-skills.py — do not edit by hand) -->")
END = "<!-- PRELOADED-SKILLS:END -->"

# Sits between BEGIN and the first skill body.  The skills index in the system
# prompt tells the model it "MUST load" a relevant skill with skill_view();
# without a counter-instruction this strong it does so anyway and the round
# trips come straight back.
PREAMBLE = """\
# Preloaded skills

The complete text of the skills below is reproduced here, in full. They are
already in your context — you have them, right now, in this message.

**Do not call `skill_view` for any skill listed here.** It returns exactly the
text you are already reading, and the call costs a round trip to the model,
which is the single largest source of latency in this deployment. The skills
index elsewhere in this prompt says you must load a relevant skill before
acting on it; for these skills that instruction is already satisfied.

`skill_view` remains correct for a skill that is *not* in this list.

Treat each section below exactly as you would treat the skill it came from:
these are your operating instructions, not reference material.
"""


def strip_frontmatter(text: str) -> str:
    """Drop a leading ``---`` delimited YAML block.

    The frontmatter is machine metadata (name, version, tags,
    required_environment_variables); the model is served by the body.
    """
    text = text.lstrip("﻿")
    if not text.startswith("---"):
        return text
    end = text.find("\n---", 3)
    if end == -1:
        return text
    return text[end + 4:].lstrip("\n")


def render_block(skills_dir: Path, names: list[str]) -> tuple[str, list[str]]:
    """Return (block_body, missing_skill_names)."""
    parts: list[str] = [PREAMBLE]
    missing: list[str] = []
    for name in names:
        path = skills_dir / name / "SKILL.md"
        if not path.is_file():
            missing.append(name)
            continue
        body = strip_frontmatter(path.read_text(encoding="utf-8")).strip()
        if not body:
            missing.append(name)
            continue
        # The skill's own headings start at ##, so a ## wrapper would collide.
        # Fence the name instead of nesting, and keep it greppable.
        parts.append(f"---\n\n# Skill: `{name}`\n\n{body}")
    return "\n\n".join(parts) + "\n", missing


def splice(soul: str, block: str) -> str:
    """Replace the managed block in *soul*, or append it."""
    managed = f"{BEGIN}\n{block}{END}\n"
    start = soul.find(BEGIN)
    if start != -1:
        stop = soul.find(END, start)
        if stop != -1:
            return soul[:start] + managed + soul[stop + len(END) + 1:].lstrip("\n")
        # BEGIN without END: a truncated write. Everything after BEGIN is
        # ours anyway, so drop it rather than nesting a second block.
        return soul[:start] + managed
    return soul.rstrip("\n") + "\n\n" + managed


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--soul", required=True, type=Path)
    ap.add_argument("--skills-dir", required=True, type=Path)
    ap.add_argument("--skills", required=True,
                    help="comma-separated skill names, in the order to inline")
    args = ap.parse_args()

    names = [n.strip() for n in args.skills.split(",") if n.strip()]
    if not names:
        print("preload-skills: no skills requested, nothing to do")
        return 0

    if not args.soul.is_file():
        print(f"preload-skills: no SOUL.md at {args.soul}, skipping",
              file=sys.stderr)
        return 0
    if not args.skills_dir.is_dir():
        print(f"preload-skills: no skills dir at {args.skills_dir}, skipping",
              file=sys.stderr)
        return 0

    block, missing = render_block(args.skills_dir, names)
    for name in missing:
        print(f"preload-skills: WARNING skill not found or empty: {name}",
              file=sys.stderr)

    inlined = len(names) - len(missing)
    if not inlined:
        print("preload-skills: nothing inlined, SOUL.md left unchanged",
              file=sys.stderr)
        return 0

    soul = args.soul.read_text(encoding="utf-8")
    updated = splice(soul, block)
    if updated == soul:
        print(f"preload-skills: SOUL.md already current "
              f"({inlined} skill(s), {len(block):,} chars)")
        return 0

    # Write via a temp file in the same dir so a crash mid-write cannot leave
    # the agent with a half-written identity prompt.
    tmp = args.soul.with_suffix(".md.preload-tmp")
    tmp.write_text(updated, encoding="utf-8")
    tmp.replace(args.soul)
    print(f"preload-skills: inlined {inlined} skill(s), {len(block):,} chars "
          f"into {args.soul} (SOUL.md now {len(updated):,} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
