#!/usr/bin/env python3
"""Refresh the committed snapshot of the public RGS+ FAQ.

    python3 scripts/fetch-faq.py            # show what changed, don't write
    python3 scripts/fetch-faq.py --write    # update the snapshot
    python3 scripts/fetch-faq.py --markdown faq.md   # dump readable markdown

The running bot does NOT depend on this script: the plugin re-fetches
rgsplus.com/faq itself once its cache goes stale. The snapshot it maintains is
the cold-start and offline fallback, and its git diff is the useful part --
it is the only record of what RGS+ changed on their public FAQ, which matters
because those answers quote prices and response times the bot repeats to
customers.

Run it when you want to see whether the FAQ moved, and commit the result so
the fallback does not drift years behind the live page.

Parsing lives in library/tools/support/rgsplus-faq/__init__.py and is imported
here rather than reimplemented, so the snapshot and the live fetch can never
disagree about structure. Stdlib only.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PLUGIN = REPO / "library" / "tools" / "support" / "rgsplus-faq" / "__init__.py"


def load_plugin():
    spec = importlib.util.spec_from_file_location("rgsplus_faq", PLUGIN)
    if spec is None or spec.loader is None:
        sys.exit(f"cannot load the FAQ plugin at {PLUGIN}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def to_markdown(payload: dict) -> str:
    by_cat: dict[str, list[dict]] = {}
    for item in payload["items"]:
        for cat in item["categories"] or ["Overig"]:
            by_cat.setdefault(cat, []).append(item)

    out = [
        "# RGS+ FAQ",
        "",
        f"Source: {payload['source_url']}",
        f"Fetched: {payload['fetched_at']}",
        f"Entries: {payload['item_count']}",
        "",
        "Generated by scripts/fetch-faq.py. Do not edit by hand.",
        "",
    ]
    for cat, items in by_cat.items():
        out.append(f"## {cat}\n")
        for item in items:
            out.append(f"### {item['question']}\n")
            out.append(item["answer"] + "\n")
            out.append(f"<{item['url']}>\n")
    return "\n".join(out)


def diff(old: dict | None, new: dict) -> int:
    """Print what changed. Returns the number of differences."""
    old_items = {i["id"]: i for i in (old or {}).get("items", [])}
    new_items = {i["id"]: i for i in new["items"]}

    added = [i for k, i in new_items.items() if k not in old_items]
    removed = [i for k, i in old_items.items() if k not in new_items]
    changed = [
        (old_items[k], i) for k, i in new_items.items()
        if k in old_items and (
            old_items[k]["answer"] != i["answer"]
            or old_items[k]["question"] != i["question"]
        )
    ]

    if old is None:
        print(f"No snapshot yet — {len(new_items)} entries would be written.")
        return len(new_items)

    for item in added:
        print(f"  + NEW      [{'/'.join(item['categories'])}] {item['question']}")
    for item in removed:
        print(f"  - REMOVED  [{'/'.join(item['categories'])}] {item['question']}")
    for before, after in changed:
        print(f"  ~ CHANGED  {after['question']}")
        if before["question"] != after["question"]:
            print(f"      question was: {before['question']}")
        if before["answer"] != after["answer"]:
            print(f"      was: {before['answer'][:160]}")
            print(f"      now: {after['answer'][:160]}")

    total = len(added) + len(removed) + len(changed)
    print("  (no content changes)" if not total else f"  {total} change(s)")
    return total


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true",
                    help="write the refreshed snapshot next to the plugin")
    ap.add_argument("--markdown", metavar="PATH",
                    help="also write the FAQ as readable markdown")
    ap.add_argument("--url", help="override the FAQ URL (default rgsplus.com/faq)")
    args = ap.parse_args()

    faq = load_plugin()
    snapshot_path = faq._SNAPSHOT

    print(f"Fetching {args.url or faq.DEFAULT_URL} ...")
    payload, err = faq.fetch_live(args.url)
    if err:
        print(f"FAILED: {err}", file=sys.stderr)
        return 1

    print(f"Parsed {payload['item_count']} unique entries "
          f"across {len({c for i in payload['items'] for c in i['categories']})} categories.")

    # Canary: the page's own structured data should roughly agree with what we
    # parsed out of the markup. It is never exact -- the JSON-LD has carried an
    # entry the page does not render, and it has no categories -- so only a
    # real gap is worth reporting.
    declared = payload.get("jsonld_question_count")
    if declared and abs(declared - payload["item_count"]) > 3:
        print(f"WARNING: the page's JSON-LD declares {declared} questions but "
              f"the parser found {payload['item_count']}. The markup may have "
              f"changed — check the parser before committing this.",
              file=sys.stderr)

    old = faq._read_json(snapshot_path)
    print(f"\nAgainst {snapshot_path.relative_to(REPO)}:")
    changes = diff(old, payload)

    if args.markdown:
        Path(args.markdown).write_text(to_markdown(payload), encoding="utf-8")
        print(f"\nWrote markdown to {args.markdown}")

    if not args.write:
        print("\nDry run — pass --write to update the snapshot.")
        return 0

    # fetched_epoch is deliberately dropped: it would churn the diff on every
    # run and make a no-op refresh look like a change. The plugin treats a
    # snapshot without it as "age unknown", which is correct for a file whose
    # age is really its git history.
    stored = {k: v for k, v in payload.items() if k != "fetched_epoch"}
    snapshot_path.write_text(
        json.dumps(stored, ensure_ascii=False, indent=2, sort_keys=False) + "\n",
        encoding="utf-8",
    )
    print(f"\nWrote {snapshot_path.relative_to(REPO)} "
          f"({payload['item_count']} entries, {changes} change(s)).")
    print("Commit it: the diff is the record of what RGS+ changed on their FAQ.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
